name: contact_angle_app
description: A Flutter app for measuring contact angles of water droplets.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  opencv_dart: ^1.3.0
  ml_algo: ^16.18.0
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.1
  photo_view: ^0.15.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
    - assets/

# Launcher icon generation config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon.png"